name: Publish release
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Downgrade Gradle wrapper
        run: |
          chmod +x ./gradlew
          sed -i 's/gradle-[0-9.]*-bin.zip/gradle-7.6.4-bin.zip/' gradle/wrapper/gradle-wrapper.properties
          ./gradlew wrapper --gradle-version 7.6.4
      - name: Publish package
        run: ./gradlew -Pversion=${{ github.event.release.tag_name }} build publish
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_USERNAME: Gamer08YT
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
